name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  terraform_directory: 
    description: 'where to execute terraform'
    required: true
  terraform_sa: 
    description: 'GCP service account for Terraform'
    required: true
  terraform_version: 
    description: 'GCP Terraform Version'
    required: true
    default: 1.2.9
  github_token: 
    description: 'github secret'
    required: true
  google_sa_key:
    description: 'JSON key for GCP service account'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraforom_version }}
        terraform_wrapper: false

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: ${{ inputs.terraform_sa }}
        credentials_json: ${{ inputs.google_sa_key }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0.6.0'

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Download Plan
      id: download-plan
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github_token }}
        workflow: plan.yml
        pr: ${{ inputs.pr_id }}
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'apply<<EOF' >> $GITHUB_OUTPUT
        terraform apply -input=false -no-color tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Comment Apply
      id: comment-apply
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Apply:

          ```
          ${{ steps.apply.outputs.apply }}
          ```